export const PRODUCTS = [
  {
    id: 1,
    name: "Black Breeze",
    category: "outerwear",
    color: "black",
    price: 750,
    image: "/sisies-black-breeze.jpg",
    description: "Effortlessly chic black zip-up",
    sizes: ["One Size"],
    additionalImages: [
      "/images/black-20breeze-202.jpeg",
      "/images/black-20breeze-203.jpeg",
      "/images/black-20breeze-204.jpeg",
      "/images/black-20breeze-205.jpeg",
    ],
  },
  {
    id: 2,
    name: "Royal Cape",
    category: "outerwear",
    color: "olive",
    price: 900,
    image: "/sisies-royal-cape.jpg",
    description: "Elegant olive green cape with luxurious drape",
    sizes: ["One Size"],
    additionalImages: ["/images/olive-20royal-20cape-203.jpeg", "/images/olive-20royal-20cape-202-20.jpeg"],
  },
  {
    id: 3,
    name: "Vanilla Haven Cape",
    category: "outerwear",
    color: "cream",
    price: 1200,
    image: "/sisies-vanilla-cape.jpg",
    description: "Creamy white oversized cape with statement collar",
    sizes: ["One Size"],
    additionalImages: [
      "/images/vanilla-20haven-204.jpeg",
      "/images/vanilla-20haven-205.jpeg",
      "/images/vanilla-20heaven-202.jpeg",
      "/images/vanilla-20haven-203.jpeg",
    ],
  },
  {
    id: 4,
    name: "Trench Coat",
    category: "outerwear",
    color: "olive",
    price: 1300,
    image: "/sisies-trench-coat.jpg",
    description: "Classic olive trench coat with tailored fit",
    sizes: ["One Size"],
    additionalImages: [],
  },
  {
    id: 5,
    name: "Wrapet jacket",
    category: "outerwear",
    color: "gray",
    price: 1100,
    image: "/sisies-wrapped-jacket-gray.jpg",
    description: "Cozy gray wrapped jacket for effortless style",
    sizes: ["One Size"],
    additionalImages: [
      "/images/gray-20wrapet-20jacket-202.jpeg",
      "/images/gray-20wrapet-20jacket-203.jpeg",
      "/images/gray-20wrapet-20jacket-204.jpeg",
    ],
  },
  {
    id: 6,
    name: "Wrapet jacket",
    category: "outerwear",
    color: "brown",
    price: 1100,
    image: "/sisies-wrapped-jacket-brown.jpg",
    description: "Warm brown wrapped jacket for layered looks",
    sizes: ["One Size"],
    additionalImages: [
      "/images/brown-20wrapet-20jacket-202.jpeg",
      "/images/brown-20wrapet-20jacket-203.jpeg",
      "/images/brown-20wrapet-20jacket-204.jpeg",
    ],
  },
  {
    id: 7,
    name: "Royal Cape",
    category: "outerwear",
    color: "black",
    price: 900,
    image: "/99.jpeg",
    description: "Luxurious black royal cape with elegant drape",
    sizes: ["One Size"],
    additionalImages: [
      "/images/black-20royal-20capr-202.jpeg",
      "/images/black-20royal-20cape-203.jpeg",
      "/images/black-20royal-20cape-204.jpeg",
    ],
  },
  {
    id: 8,
    name: "Midi Slip Dress",
    category: "dresses",
    color: "dusty-rose",
    price: 139,
    image: "/slip-dress-elegant.jpg",
    description: "Minimalist slip dress in dusty rose",
    sizes: ["XS", "S", "M", "L", "XL"],
    reviews: 18,
    additionalImages: [],
  },
]
