export const PRODUCTS = [
  {
    id: 1,
    name: "Black Breeze",
    category: "outerwear",
    collection: "winter",
    color: "black",
    price: 375,
    originalPrice: 750,
    image: "/sisies-black-breeze.jpg",
    description: "Effortlessly chic black zip-up",
    sizes: ["One Size"],
    colorVariants: [
      { color: "black", productId: 1 },
      { color: "mint", productId: 11 },
      { color: "burgundy", productId: 12 },
    ],
    additionalImages: [
      "/images/black-20breeze-202.jpeg",
      "/images/black-20breeze-203.jpeg",
      "/images/black-20breeze-204.jpeg",
      "/images/black-20breeze-205.jpeg",
    ],
  },
  {
    id: 2,
    name: "Royal Cape",
    category: "outerwear",
    collection: "winter",
    color: "olive",
    price: 450,
    originalPrice: 900,
    image: "/sisies-royal-cape.jpg",
    description: "Elegant olive green cape with luxurious drape",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 2 },
      { color: "black", productId: 7 },
    ],
    additionalImages: ["/images/olive-20royal-20cape-203.jpeg", "/images/olive-20royal-20cape-202-20.jpeg"],
  },
  {
    id: 3,
    name: "Vanilla Haven Cape",
    category: "outerwear",
    collection: "winter",
    color: "cream",
    price: 600,
    originalPrice: 1200,
    image: "/sisies-vanilla-cape.jpg",
    description: "Creamy white oversized cape with statement collar",
    sizes: ["One Size"],
    additionalImages: [
      "/images/vanilla-20haven-204.jpeg",
      "/images/vanilla-20haven-205.jpeg",
      "/images/vanilla-20heaven-202.jpeg",
      "/images/vanilla-20haven-203.jpeg",
    ],
  },
  {
    id: 4,
    name: "Trench Coat",
    category: "outerwear",
    collection: "winter",
    color: "olive",
    price: 650,
    originalPrice: 1300,
    image: "/images/olive-trench-coat-1.jpg",
    description: "Classic olive trench coat with tailored fit and double-breasted buttons",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 4 },
      { color: "beige", productId: 9 },
    ],
    additionalImages: [
      "/images/olive-trench-coat-2.jpg",
      "/images/olive-trench-coat-3.jpg",
      "/images/olive-trench-coat-4.jpg",
      "/images/olive-trench-coat-5.jpg",
      "/images/olive-trench-coat-6.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 5,
    name: "Wrapet Jacket",
    category: "outerwear",
    collection: "winter",
    color: "gray",
    price: 550,
    originalPrice: 1100,
    image: "/sisies-wrapped-jacket-gray.jpg",
    description: "Cozy gray wrapped jacket for effortless style",
    sizes: ["One Size"],
    colorVariants: [
      { color: "gray", productId: 5 },
      { color: "brown", productId: 6 },
    ],
    additionalImages: [
      "/images/gray-20wrapet-20jacket-202.jpeg",
      "/images/gray-20wrapet-20jacket-203.jpeg",
      "/images/gray-20wrapet-20jacket-204.jpeg",
    ],
  },
  {
    id: 6,
    name: "Wrapet Jacket",
    category: "outerwear",
    collection: "winter",
    color: "brown",
    price: 550,
    originalPrice: 1100,
    image: "/sisies-wrapped-jacket-brown.jpg",
    description: "Warm brown wrapped jacket for layered looks",
    sizes: ["One Size"],
    colorVariants: [
      { color: "gray", productId: 5 },
      { color: "brown", productId: 6 },
    ],
    additionalImages: [
      "/images/brown-20wrapet-20jacket-202.jpeg",
      "/images/brown-20wrapet-20jacket-203.jpeg",
      "/images/brown-20wrapet-20jacket-204.jpeg",
    ],
  },
  {
    id: 7,
    name: "Royal Cape",
    category: "outerwear",
    collection: "winter",
    color: "black",
    price: 450,
    originalPrice: 900,
    image: "/99.jpeg",
    description: "Luxurious black royal cape with elegant drape",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 2 },
      { color: "black", productId: 7 },
    ],
    additionalImages: [
      "/images/black-20royal-20capr-202.jpeg",
      "/images/black-20royal-20cape-203.jpeg",
      "/images/black-20royal-20cape-204.jpeg",
    ],
  },
  {
    id: 8,
    name: "Midi Slip Dress",
    category: "dresses",
    collection: "winter",
    color: "dusty-rose",
    price: 139,
    image: "/slip-dress-elegant.jpg",
    description: "Minimalist slip dress in dusty rose",
    sizes: ["XS", "S", "M", "L", "XL"],
    reviews: 18,
    additionalImages: [],
  },
  {
    id: 9,
    name: "Trench Coat",
    category: "outerwear",
    collection: "winter",
    color: "beige",
    price: 650,
    originalPrice: 1300,
    image: "/images/beige-trench-coat-1.jpeg",
    description: "Elegant beige trench coat with tailored fit and double-breasted buttons",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 4 },
      { color: "beige", productId: 9 },
    ],
    additionalImages: [
      "/images/beige-trench-coat-2.jpeg",
      "/images/beige-trench-coat-3.jpeg",
      "/images/beige-trench-coat-4.jpeg",
      "/images/beige-trench-coat-5.jpeg",
      "/images/beige-trench-coat-6.jpeg",
      "/images/beige-trench-coat-7.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 10,
    name: "CEO Coat",
    category: "outerwear",
    collection: "winter",
    color: "creamy",
    price: 650,
    originalPrice: 1300,
    image: "/images/ceo-coat-1.jpeg",
    description: "Luxurious creamy wool coat with double-breasted buttons for a sophisticated executive look",
    sizes: ["One Size"],
    additionalImages: [
      "/images/ceo-coat-2.jpeg",
      "/images/ceo-coat-3.jpeg",
      "/images/ceo-coat-4.jpeg",
      "/images/ceo-coat-5.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 11,
    name: "Mint Breeze",
    category: "outerwear",
    collection: "winter",
    color: "mint",
    price: 375,
    originalPrice: 750,
    image: "/images/mint-breeze-1.jpeg",
    description: "Fresh mint green ribbed zip-up sweater for a refreshing look",
    sizes: ["One Size"],
    colorVariants: [
      { color: "black", productId: 1 },
      { color: "mint", productId: 11 },
      { color: "burgundy", productId: 12 },
    ],
    additionalImages: [
      "/images/mint-breeze-2.jpeg",
      "/images/mint-breeze-3.jpeg",
      "/images/mint-breeze-4.jpeg",
      "/images/mint-breeze-5.jpeg",
      "/images/mint-breeze-6.jpeg",
      "/images/mint-breeze-7.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 12,
    name: "Burgundy Breeze",
    category: "outerwear",
    collection: "winter",
    color: "burgundy",
    price: 375,
    originalPrice: 750,
    image: "/images/burgundy-breeze-1.jpeg",
    description: "Rich burgundy ribbed zip-up sweater for a bold, warm look",
    sizes: ["One Size"],
    colorVariants: [
      { color: "black", productId: 1 },
      { color: "mint", productId: 11 },
      { color: "burgundy", productId: 12 },
    ],
    additionalImages: [
      "/images/burgundy-breeze-2.jpeg",
      "/images/burgundy-breeze-3.jpeg",
      "/images/burgundy-breeze-4.jpeg",
      "/images/burgundy-breeze-5.jpeg",
      "/images/burgundy-breeze-size-chart.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 13,
    name: "Lail",
    category: "abayas",
    collection: "ramadan",
    color: "black",
    price: 1599,
    originalPrice: 2499,
    image: "/images/lail-1.png",
    description: "A classic black kaftan with a loose, flowing fit and wide sleeves adorned with soft fringe details. Simple, elegant, and effortlessly chic — perfect for evening gatherings and timeless looks.",
    sizes: ["One Size"],
    additionalImages: [
      "/images/lail-2.png",
      "/images/lail-3.png",
      "/images/lail-4.png",
      "/images/lail-5.png",
      "/images/lail-6.png",
    ],
    isNewArrival: true,
  },
  {
    id: 14,
    name: "Masterpiece",
    category: "abayas",
    collection: "ramadan",
    color: "beige",
    price: 2799,
    originalPrice: 3499,
    image: "/images/moonlight-1.png",
    description: "A soft beige kaftan with a elegant fit, highlighted by vibrant patterned sleeves. The detailed geometric design adds a colorful, artistic touch while keeping the overall look classy and effortless — perfect for stylish everyday wear or special gatherings.",
    sizes: ["One Size"],
    colorVariants: [
      { color: "beige", productId: 14 },
      { color: "black", productId: 15 },
    ],
    additionalImages: [
      "/images/moonlight-2.png",
      "/images/moonlight-3.png",
      "/images/masterpiece-beige-4.png",
      "/images/masterpiece-beige-5.png",
    ],
    isNewArrival: true,
    soldOut: true,
  },
  {
    id: 15,
    name: "Masterpiece",
    category: "abayas",
    collection: "ramadan",
    color: "black",
    price: 2799,
    originalPrice: 3499,
    image: "/images/masterpiece-black-1.png",
    description: "A soft black kaftan with a relaxed, elegant fit, highlighted by vibrant patterned sleeves. The detailed geometric design adds a colorful, artistic touch while keeping the overall look classy and effortless — perfect for stylish everyday wear or special gatherings.",
    sizes: ["One Size"],
    colorVariants: [
      { color: "beige", productId: 14 },
      { color: "black", productId: 15 },
    ],
    additionalImages: [
      "/images/masterpiece-black-2.png",
      "/images/masterpiece-black-3.png",
      "/images/masterpiece-black-4.png",
      "/images/masterpiece-black-5.png",
    ],
    isNewArrival: true,
  },
  {
    id: 16,
    name: "Moonlight",
    category: "abayas",
    collection: "ramadan",
    color: "beige",
    price: 1599,
    originalPrice: 1999,
    image: "/images/moonlight-6.png",
    description: "A beige kaftan with a loose, flowy silhouette and wide sleeves, designed for comfort and elegance. The subtle crescent details scattered across the fabric add a soft, unique touch, making it simple yet distinctive — perfect for effortless, graceful styling",
    sizes: ["One Size"],
    additionalImages: [
      "/images/moonlight-4.png",
      "/images/moonlight-5.png",
      "/images/moonlight-7.png",
      "/images/moonlight-8.png",
      "/images/moonlight-9.png",
      "/images/moonlight-10.png",
    ],
    isNewArrival: true,
  },
  {
    id: 17,
    name: "Arabic Calligraphy",
    category: "abayas",
    collection: "ramadan",
    color: "black",
    price: 1650,
    originalPrice: 2199,
    image: "/images/arabic-calligraphy-1.png",
    description: "A black kaftan with a loose, flowing fit, finished with gold lining and simple embroidered details on the edges. Elegant and easy to wear — perfect for special evenings and gatherings",
    sizes: ["One Size"],
    additionalImages: [
      "/images/arabic-calligraphy-2.png",
      "/images/arabic-calligraphy-3.png",
      "/images/arabic-calligraphy-4.png",
      "/images/arabic-calligraphy-5.png",
    ],
    isNewArrival: true,
  },
  {
    id: 18,
    name: "Glimmer Set",
    category: "sets",
    collection: "summer",
    color: "yellow",
    price: 2200,
    image: "/images/glimmer-set-yellow-1.jpg",
    description: "Luxurious yellow glimmer set with shimmering details and flowing silhouette for an effortless summer look",
    sizes: ["One Size"],
    colorVariants: [
      { color: "yellow", productId: 18 },
      { color: "brown", productId: 19 },
    ],
    additionalImages: [
      "/images/glimmer-set-yellow-2.jpg",
      "/images/glimmer-set-yellow-3.jpg",
      "/images/glimmer-set-yellow-4.jpg",
      "/images/glimmer-set-yellow-5.jpg",
      "/images/glimmer-set-yellow-6.jpg",
    ],
    isNewArrival: true,
  },
  {
    id: 19,
    name: "Glimmer Set",
    category: "sets",
    collection: "summer",
    color: "brown",
    price: 2200,
    image: "/images/glimmer-set-brown-1.jpg",
    description: "Elegant brown glimmer set with shimmering details and flowing silhouette for a sophisticated summer style",
    sizes: ["One Size"],
    colorVariants: [
      { color: "yellow", productId: 18 },
      { color: "brown", productId: 19 },
    ],
    additionalImages: [
      "/images/glimmer-set-brown-2.jpg",
      "/images/glimmer-set-brown-3.jpg",
      "/images/glimmer-set-brown-4.jpg",
    ],
    isNewArrival: true,
  },
]
