export const PRODUCTS = [
  {
    id: 1,
    name: "Black Breeze",
    category: "outerwear",
    collection: "winter",
    color: "black",
    price: 750,
    image: "/sisies-black-breeze.jpg",
    description: "Effortlessly chic black zip-up",
    sizes: ["One Size"],
    colorVariants: [
      { color: "black", productId: 1 },
      { color: "mint", productId: 11 },
      { color: "burgundy", productId: 12 },
    ],
    additionalImages: [
      "/images/black-20breeze-202.jpeg",
      "/images/black-20breeze-203.jpeg",
      "/images/black-20breeze-204.jpeg",
      "/images/black-20breeze-205.jpeg",
    ],
  },
  {
    id: 2,
    name: "Royal Cape",
    category: "outerwear",
    collection: "winter",
    color: "olive",
    price: 900,
    image: "/sisies-royal-cape.jpg",
    description: "Elegant olive green cape with luxurious drape",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 2 },
      { color: "black", productId: 7 },
    ],
    additionalImages: ["/images/olive-20royal-20cape-203.jpeg", "/images/olive-20royal-20cape-202-20.jpeg"],
  },
  {
    id: 3,
    name: "Vanilla Haven Cape",
    category: "outerwear",
    collection: "winter",
    color: "cream",
    price: 1200,
    image: "/sisies-vanilla-cape.jpg",
    description: "Creamy white oversized cape with statement collar",
    sizes: ["One Size"],
    additionalImages: [
      "/images/vanilla-20haven-204.jpeg",
      "/images/vanilla-20haven-205.jpeg",
      "/images/vanilla-20heaven-202.jpeg",
      "/images/vanilla-20haven-203.jpeg",
    ],
  },
  {
    id: 4,
    name: "Trench Coat",
    category: "outerwear",
    collection: "winter",
    color: "olive",
    price: 1300,
    image: "/images/olive-trench-coat-1.jpg",
    description: "Classic olive trench coat with tailored fit and double-breasted buttons",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 4 },
      { color: "beige", productId: 9 },
    ],
    additionalImages: [
      "/images/olive-trench-coat-2.jpg",
      "/images/olive-trench-coat-3.jpg",
      "/images/olive-trench-coat-4.jpg",
      "/images/olive-trench-coat-5.jpg",
      "/images/olive-trench-coat-6.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 5,
    name: "Wrapet Jacket",
    category: "outerwear",
    collection: "winter",
    color: "gray",
    price: 1100,
    image: "/sisies-wrapped-jacket-gray.jpg",
    description: "Cozy gray wrapped jacket for effortless style",
    sizes: ["One Size"],
    colorVariants: [
      { color: "gray", productId: 5 },
      { color: "brown", productId: 6 },
    ],
    additionalImages: [
      "/images/gray-20wrapet-20jacket-202.jpeg",
      "/images/gray-20wrapet-20jacket-203.jpeg",
      "/images/gray-20wrapet-20jacket-204.jpeg",
    ],
  },
  {
    id: 6,
    name: "Wrapet Jacket",
    category: "outerwear",
    collection: "winter",
    color: "brown",
    price: 1100,
    image: "/sisies-wrapped-jacket-brown.jpg",
    description: "Warm brown wrapped jacket for layered looks",
    sizes: ["One Size"],
    colorVariants: [
      { color: "gray", productId: 5 },
      { color: "brown", productId: 6 },
    ],
    additionalImages: [
      "/images/brown-20wrapet-20jacket-202.jpeg",
      "/images/brown-20wrapet-20jacket-203.jpeg",
      "/images/brown-20wrapet-20jacket-204.jpeg",
    ],
  },
  {
    id: 7,
    name: "Royal Cape",
    category: "outerwear",
    collection: "winter",
    color: "black",
    price: 900,
    image: "/99.jpeg",
    description: "Luxurious black royal cape with elegant drape",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 2 },
      { color: "black", productId: 7 },
    ],
    additionalImages: [
      "/images/black-20royal-20capr-202.jpeg",
      "/images/black-20royal-20cape-203.jpeg",
      "/images/black-20royal-20cape-204.jpeg",
    ],
  },
  {
    id: 8,
    name: "Midi Slip Dress",
    category: "dresses",
    collection: "winter",
    color: "dusty-rose",
    price: 139,
    image: "/slip-dress-elegant.jpg",
    description: "Minimalist slip dress in dusty rose",
    sizes: ["XS", "S", "M", "L", "XL"],
    reviews: 18,
    additionalImages: [],
  },
  {
    id: 9,
    name: "Trench Coat",
    category: "outerwear",
    collection: "winter",
    color: "beige",
    price: 1300,
    image: "/images/beige-trench-coat-1.jpeg",
    description: "Elegant beige trench coat with tailored fit and double-breasted buttons",
    sizes: ["One Size"],
    colorVariants: [
      { color: "olive", productId: 4 },
      { color: "beige", productId: 9 },
    ],
    additionalImages: [
      "/images/beige-trench-coat-2.jpeg",
      "/images/beige-trench-coat-3.jpeg",
      "/images/beige-trench-coat-4.jpeg",
      "/images/beige-trench-coat-5.jpeg",
      "/images/beige-trench-coat-6.jpeg",
      "/images/beige-trench-coat-7.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 10,
    name: "CEO Coat",
    category: "outerwear",
    collection: "winter",
    color: "creamy",
    price: 1300,
    image: "/images/ceo-coat-1.jpeg",
    description: "Luxurious creamy wool coat with double-breasted buttons for a sophisticated executive look",
    sizes: ["One Size"],
    additionalImages: [
      "/images/ceo-coat-2.jpeg",
      "/images/ceo-coat-3.jpeg",
      "/images/ceo-coat-4.jpeg",
      "/images/ceo-coat-5.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 11,
    name: "Mint Breeze",
    category: "outerwear",
    collection: "winter",
    color: "mint",
    price: 750,
    image: "/images/mint-breeze-1.jpeg",
    description: "Fresh mint green ribbed zip-up sweater for a refreshing look",
    sizes: ["One Size"],
    colorVariants: [
      { color: "black", productId: 1 },
      { color: "mint", productId: 11 },
      { color: "burgundy", productId: 12 },
    ],
    additionalImages: [
      "/images/mint-breeze-2.jpeg",
      "/images/mint-breeze-3.jpeg",
      "/images/mint-breeze-4.jpeg",
      "/images/mint-breeze-5.jpeg",
      "/images/mint-breeze-6.jpeg",
      "/images/mint-breeze-7.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 12,
    name: "Burgundy Breeze",
    category: "outerwear",
    collection: "winter",
    color: "burgundy",
    price: 750,
    image: "/images/burgundy-breeze-1.jpeg",
    description: "Rich burgundy ribbed zip-up sweater for a bold, warm look",
    sizes: ["One Size"],
    colorVariants: [
      { color: "black", productId: 1 },
      { color: "mint", productId: 11 },
      { color: "burgundy", productId: 12 },
    ],
    additionalImages: [
      "/images/burgundy-breeze-2.jpeg",
      "/images/burgundy-breeze-3.jpeg",
      "/images/burgundy-breeze-4.jpeg",
      "/images/burgundy-breeze-5.jpeg",
      "/images/burgundy-breeze-size-chart.jpeg",
    ],
    isNewArrival: true,
  },
  {
    id: 13,
    name: "Lail",
    category: "abayas",
    collection: "ramadan",
    color: "black",
    price: 1950,
    image: "/images/lail-1.png",
    description: "Luxurious black abaya with shimmering beaded fringe details, satin lining, and an elegant hooded silhouette - perfect for Ramadan gatherings",
    sizes: ["One Size"],
    additionalImages: [
      "/images/lail-2.png",
      "/images/lail-3.png",
      "/images/lail-4.png",
      "/images/lail-5.png",
      "/images/lail-6.png",
    ],
    isNewArrival: true,
  },
  {
    id: 14,
    name: "Masterpiece",
    category: "abayas",
    collection: "ramadan",
    color: "beige",
    price: 2770,
    image: "/images/moonlight-1.png",
    description: "Elegant beige open abaya with stunning hand-embroidered patchwork bell sleeves featuring vibrant geometric patterns and gold accents",
    sizes: ["One Size"],
    colorVariants: [
      { color: "beige", productId: 14 },
      { color: "black", productId: 15 },
    ],
    additionalImages: [
      "/images/moonlight-2.png",
      "/images/moonlight-3.png",
      "/images/moonlight-4.png",
      "/images/moonlight-5.png",
      "/images/masterpiece-beige-4.png",
      "/images/masterpiece-beige-5.png",
    ],
    isNewArrival: true,
  },
  {
    id: 15,
    name: "Masterpiece",
    category: "abayas",
    collection: "ramadan",
    color: "black",
    price: 2770,
    image: "/images/masterpiece-black-1.png",
    description: "Luxurious black velvet open abaya with stunning hand-embroidered patchwork bell sleeves featuring vibrant geometric patterns and gold accents",
    sizes: ["One Size"],
    colorVariants: [
      { color: "beige", productId: 14 },
      { color: "black", productId: 15 },
    ],
    additionalImages: [
      "/images/masterpiece-black-2.png",
      "/images/masterpiece-black-3.png",
      "/images/masterpiece-black-4.png",
      "/images/masterpiece-black-5.png",
    ],
    isNewArrival: true,
  },
  {
    id: 16,
    name: "Moonlight",
    category: "abayas",
    collection: "ramadan",
    color: "beige",
    price: 1400,
    image: "/images/moonlight-7.png",
    description: "Elegant beige open abaya adorned with delicate embroidered crescent moons in brown and gold, featuring flowing bell sleeves",
    sizes: ["One Size"],
    additionalImages: [
      "/images/moonlight-4.png",
      "/images/moonlight-5.png",
      "/images/moonlight-6.png",
      "/images/moonlight-8.png",
      "/images/moonlight-9.png",
      "/images/moonlight-10.png",
    ],
    isNewArrival: true,
  },
  {
    id: 17,
    name: "Arabic Calligraphy",
    category: "abayas",
    collection: "ramadan",
    color: "black",
    price: 1650,
    image: "/images/arabic-calligraphy-1.png",
    description: "Luxurious black velvet abaya with golden Arabic calligraphy trim and champagne satin lining, a statement piece for Ramadan nights",
    sizes: ["One Size"],
    additionalImages: [
      "/images/arabic-calligraphy-2.png",
      "/images/arabic-calligraphy-3.png",
      "/images/arabic-calligraphy-4.png",
      "/images/arabic-calligraphy-5.png",
    ],
    isNewArrival: true,
  },
]
